[package]
name = "image_encryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.21.0"
rand = "0.8.5"
steganography = "1.0.2"
tokio = { version = "1.33.0", features = ["full"] }

[[bin]]
name = "encoder"
path = "src/encoder.rs"

[[bin]]
name = "decoder"
path = "src/decoder.rs"

[[bin]]
name = "main"
path = "src/main.rs"

